server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/productdb_prod
    username: prod_admin
    password: prod_secret

product:
  cache-enabled: true
  api-version: v1

logging:
  level:
    root: WARN
    com.example.productservice: WARN
