spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: root
    password: r00t@123!
  jpa:
    hibernate:
      ddl-auto: update

user:
  test:
    property: from-native
