spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: root
    password: r00t@123!
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

user:
  test:
    property: from-native
