spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: admin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: validate

user:
  test:
    property: prod-value
